### PR TITLE
parse integration fields

### PR DESCRIPTION
**Pull request by alterenzo**
Following the discussion we had on the Tech Q&A call, I am raising this PR as promised.
It has a preliminary implementation of what a parser for IntegrationFields should look like.

The `to_html` method is of course just a stub

### CODE REVIEW

**Comment by Raph22** [comment]
Hi alterenzo,
Thanks for this PR. Can you just delete `to_html` method and adding a `to_json` method which returns the json object not as string ?

**Comment by alterenzo** [comment]
Hi @Raph22 , could you expand please? If I call `to_json` on the `value` hash, it will return a String in json format, otherwise I can return the hash itself.

**Comment by alterenzo** [comment]
Hi @Raph22 I've added a new commit, could you please check if this is closer to what you were looking for? thanks

**Comment by Raph22** [comment]
Hi @alterenzo, sorry for this late answer. The latest commit is what we wanted.
Thanks !
Fix #88

**Pull request merged**
